chromestandalone:
    image: selenium/standalone-chrome
    ports:
        - "4444"
    links:
        - "web"
    dns:
        - 8.8.8.8
        - 9.9.9.9

web:
    image: nginx
    command: nginx -c /srv/www/protractor/nginx.conf
    ports:
        - "8080"
    volumes:
        - ../:/srv/www
    dns:
        - 8.8.8.8
        - 9.9.9.9

test:
    image: nodesource/trusty:0.12
    command: /srv/www/protractor/runtests.sh
    links:
        - "web"
        - "chromestandalone"
    volumes:
        - ../:/srv/www
    dns:
        - 8.8.8.8
        - 9.9.9.9
